/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        }
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in-down': 'fadeInDown 0.6s ease-out',
        'fade-in-left': 'fadeInLeft 0.6s ease-out',
        'fade-in-right': 'fadeInRight 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'slide-down': 'slideDown 0.6s ease-out',
        'slide-left': 'slideLeft 0.6s ease-out',
        'slide-right': 'slideRight 0.6s ease-out',
        'scale-in': 'scaleIn 0.5s ease-out',
        'bounce-in': 'bounceIn 0.8s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'gradient-shift': 'gradientShift 3s ease infinite',
        'wiggle': 'wiggle 0.5s ease-in-out',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'tada': 'tada 1s ease-in-out',
        'zoom-in': 'zoomIn 0.3s ease-out',
        'zoom-out': 'zoomOut 0.3s ease-out',
        'flip': 'flip 0.6s ease-out',
        'hinge': 'hinge 2s ease-in-out',
        'roll-in': 'rollIn 0.6s ease-out',
        'roll-out': 'rollOut 0.6s ease-out',
        'swing': 'swing 1s ease-in-out',
        'rubber-band': 'rubberBand 0.6s ease-out',
        'light-speed-in': 'lightSpeedIn 0.6s ease-out',
        'light-speed-out': 'lightSpeedOut 0.6s ease-out',
        'jello': 'jello 0.6s ease-out',
        'jack-in-the-box': 'jackInTheBox 0.6s ease-out',
        'fade-in-scale': 'fadeInScale 0.6s ease-out',
        'fade-in-rotate': 'fadeInRotate 0.6s ease-out',
        'fade-in-slide-up': 'fadeInSlideUp 0.8s ease-out',
        'fade-in-slide-down': 'fadeInSlideDown 0.8s ease-out',
        'fade-in-slide-left': 'fadeInSlideLeft 0.8s ease-out',
        'fade-in-slide-right': 'fadeInSlideRight 0.8s ease-out',
        'slide-up-fade': 'slideUpFade 0.6s ease-out',
        'slide-down-fade': 'slideDownFade 0.6s ease-out',
        'slide-left-fade': 'slideLeftFade 0.6s ease-out',
        'slide-right-fade': 'slideRightFade 0.6s ease-out',
        'bounce-in-up': 'bounceInUp 0.8s ease-out',
        'bounce-in-down': 'bounceInDown 0.8s ease-out',
        'bounce-in-left': 'bounceInLeft 0.8s ease-out',
        'bounce-in-right': 'bounceInRight 0.8s ease-out',
        'rotate-in': 'rotateIn 0.6s ease-out',
        'rotate-in-up-left': 'rotateInUpLeft 0.6s ease-out',
        'rotate-in-up-right': 'rotateInUpRight 0.6s ease-out',
        'rotate-in-down-left': 'rotateInDownLeft 0.6s ease-out',
        'rotate-in-down-right': 'rotateInDownRight 0.6s ease-out',
        'flip-in-x': 'flipInX 0.6s ease-out',
        'flip-in-y': 'flipInY 0.6s ease-out',
        'flip-out-x': 'flipOutX 0.6s ease-out',
        'flip-out-y': 'flipOutY 0.6s ease-out',
        'hinge': 'hinge 2s ease-in-out',
        'roll-in': 'rollIn 0.6s ease-out',
        'roll-out': 'rollOut 0.6s ease-out',
        'swing': 'swing 1s ease-in-out',
        'rubber-band': 'rubberBand 0.6s ease-out',
        'light-speed-in': 'lightSpeedIn 0.6s ease-out',
        'light-speed-out': 'lightSpeedOut 0.6s ease-out',
        'jello': 'jello 0.6s ease-out',
        'jack-in-the-box': 'jackInTheBox 0.6s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        fadeInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1', transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(59, 130, 246, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(59, 130, 246, 0.6)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: 'calc(200px + 100%) 0' },
        },
        gradientShift: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
        },
        tada: {
          '0%': { transform: 'scale(1)' },
          '10%, 20%': { transform: 'scale(0.9) rotate(-3deg)' },
          '30%, 50%, 70%, 90%': { transform: 'scale(1.1) rotate(3deg)' },
          '40%, 60%, 80%': { transform: 'scale(1.1) rotate(-3deg)' },
          '100%': { transform: 'scale(1) rotate(0)' },
        },
        zoomIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        zoomOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0', transform: 'scale(0.3)' },
          '100%': { opacity: '0', transform: 'scale(0.3)' },
        },
        flip: {
          '0%': { transform: 'perspective(400px) rotateY(0)' },
          '40%': { transform: 'perspective(400px) rotateY(90deg)' },
          '60%': { transform: 'perspective(400px) rotateY(180deg)' },
          '100%': { transform: 'perspective(400px) rotateY(360deg)' },
        },
        hinge: {
          '0%': { transform: 'rotate(0)' },
          '20%, 60%': { transform: 'rotate(80deg)' },
          '40%, 80%': { transform: 'rotate(60deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        rollIn: {
          '0%': { opacity: '0', transform: 'translateX(-100%) rotate(-120deg)' },
          '100%': { opacity: '1', transform: 'translateX(0px) rotate(0deg)' },
        },
        rollOut: {
          '0%': { opacity: '1', transform: 'translateX(0px) rotate(0deg)' },
          '100%': { opacity: '0', transform: 'translateX(100%) rotate(120deg)' },
        },
        swing: {
          '20%': { transform: 'rotate(15deg)' },
          '40%': { transform: 'rotate(-10deg)' },
          '60%': { transform: 'rotate(5deg)' },
          '80%': { transform: 'rotate(-5deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        rubberBand: {
          '0%': { transform: 'scale(1)' },
          '30%': { transform: 'scaleX(1.25) scaleY(0.75)' },
          '40%': { transform: 'scaleX(0.75) scaleY(1.25)' },
          '60%': { transform: 'scaleX(1.15) scaleY(0.85)' },
          '100%': { transform: 'scale(1)' },
        },
        lightSpeedIn: {
          '0%': { opacity: '0', transform: 'translateX(-100%) skewX(30deg)' },
          '60%': { opacity: '1', transform: 'translateX(20%) skewX(-20deg)' },
          '80%': { transform: 'translateX(-5%) skewX(10deg)' },
          '100%': { transform: 'translateX(0deg) skewX(0deg)' },
        },
        lightSpeedOut: {
          '0%': { opacity: '1', transform: 'translateX(0deg) skewX(0deg)' },
          '100%': { opacity: '0', transform: 'translateX(100%) skewX(-30deg)' },
        },
        jello: {
          '0%, 100%': { transform: 'scale(1, 1)' },
          '30%': { transform: 'scale(1.25, 0.75)' },
          '40%': { transform: 'scale(0.75, 1.25)' },
          '50%': { transform: 'scale(1.15, 0.85)' },
          '65%': { transform: 'scale(0.95, 1.05)' },
          '75%': { transform: 'scale(1.05, 0.95)' },
        },
        jackInTheBox: {
          '0%': { opacity: '0', transform: 'scale(0.1) rotate(30deg)' },
          '50%': { transform: 'rotate(-10deg)' },
          '70%': { transform: 'rotate(3deg)' },
          '100%': { opacity: '1', transform: 'scale(1) rotate(0deg)' },
        },
        fadeInScale: {
          '0%': { opacity: '0', transform: 'scale(0.8)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        fadeInRotate: {
          '0%': { opacity: '0', transform: 'rotate(-180deg) scale(0.8)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) scale(1)' },
        },
        fadeInSlideUp: {
          '0%': { opacity: '0', transform: 'translateY(50px) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        fadeInSlideDown: {
          '0%': { opacity: '0', transform: 'translateY(-50px) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        fadeInSlideLeft: {
          '0%': { opacity: '0', transform: 'translateX(50px) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        fadeInSlideRight: {
          '0%': { opacity: '0', transform: 'translateX(-50px) scale(0.9)' },
          '100%': { opacity: '1', transform: 'translateX(0) scale(1)' },
        },
        slideUpFade: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDownFade: {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeftFade: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideRightFade: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        bounceInUp: {
          '0%': { opacity: '0', transform: 'translateY(3000px)' },
          '60%': { opacity: '1', transform: 'translateY(-20px)' },
          '80%': { transform: 'translateY(10px)' },
          '100%': { transform: 'translateY(0)' },
        },
        bounceInDown: {
          '0%': { opacity: '0', transform: 'translateY(-3000px)' },
          '60%': { opacity: '1', transform: 'translateY(20px)' },
          '80%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(0)' },
        },
        bounceInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-3000px)' },
          '60%': { opacity: '1', transform: 'translateX(20px)' },
          '80%': { transform: 'translateX(-10px)' },
          '100%': { transform: 'translateX(0)' },
        },
        bounceInRight: {
          '0%': { opacity: '0', transform: 'translateX(3000px)' },
          '60%': { opacity: '1', transform: 'translateX(-20px)' },
          '80%': { transform: 'translateX(10px)' },
          '100%': { transform: 'translateX(0)' },
        },
        rotateIn: {
          '0%': { opacity: '0', transform: 'rotate(-200deg)' },
          '100%': { opacity: '1', transform: 'rotate(0deg)' },
        },
        rotateInUpLeft: {
          '0%': { opacity: '0', transform: 'rotate(45deg) translateY(-100%)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) translateY(0)' },
        },
        rotateInUpRight: {
          '0%': { opacity: '0', transform: 'rotate(-45deg) translateY(-100%)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) translateY(0)' },
        },
        rotateInDownLeft: {
          '0%': { opacity: '0', transform: 'rotate(-45deg) translateY(100%)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) translateY(0)' },
        },
        rotateInDownRight: {
          '0%': { opacity: '0', transform: 'rotate(45deg) translateY(100%)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) translateY(0)' },
        },
        flipInX: {
          '0%': { opacity: '0', transform: 'perspective(400px) rotateX(90deg)' },
          '40%': { transform: 'perspective(400px) rotateX(-20deg)' },
          '60%': { transform: 'perspective(400px) rotateX(10deg)' },
          '80%': { transform: 'perspective(400px) rotateX(-5deg)' },
          '100%': { opacity: '1', transform: 'perspective(400px) rotateX(0deg)' },
        },
        flipInY: {
          '0%': { opacity: '0', transform: 'perspective(400px) rotateY(90deg)' },
          '40%': { transform: 'perspective(400px) rotateY(-20deg)' },
          '60%': { transform: 'perspective(400px) rotateY(10deg)' },
          '80%': { transform: 'perspective(400px) rotateY(-5deg)' },
          '100%': { opacity: '1', transform: 'perspective(400px) rotateY(0deg)' },
        },
        flipOutX: {
          '0%': { opacity: '1', transform: 'perspective(400px) rotateX(0deg)' },
          '100%': { opacity: '0', transform: 'perspective(400px) rotateX(90deg)' },
        },
        flipOutY: {
          '0%': { opacity: '1', transform: 'perspective(400px) rotateY(0deg)' },
          '100%': { opacity: '0', transform: 'perspective(400px) rotateY(90deg)' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        'glow': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-lg': '0 0 40px rgba(59, 130, 246, 0.5)',
        'glow-xl': '0 0 60px rgba(59, 130, 246, 0.7)',
        'inner-glow': 'inset 0 0 20px rgba(59, 130, 246, 0.2)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'gradient-mesh': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        'gradient-sunset': 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
        'gradient-ocean': 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
        'gradient-forest': 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
        'gradient-fire': 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
        'gradient-aurora': 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
      },
      transitionTimingFunction: {
        'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
    },
  },
  plugins: [],
} 